### ISSUE TITLE
Generate Scaffold

### ISSUE THREAD

**Issue by 2016rshah** [andreapavoni/12dos-bookmarks#1]
On the tutorial did you mean to capitalize the b in bookmark? Correct me if I'm wrong but isn't there some convention that suggests capitalizing scaffolds? 

<code>
$ rails generate scaffold Bookmark title:string url:string
</code>
as opposed to 
<code>
$ rails generate scaffold bookmark title:string url:string
</code>

**Comment by andreapavoni** [comment]
there aren't problems by issuing a scaffold command using a non-capitalized letter in the command line. you can even use `rails g scaffold my_resource foo:string bar:integer` and you'll get a `MyResource` class anyway.

**Comment by 2016rshah** [comment]
Wow I didn't know that, very interesting. Thanks for the explanation!
