### ISSUE TITLE
Association

### ISSUE THREAD

**Issue by 2016rshah** [andreapavoni/12dos-bookmarks#2]
To generate the association you suggest
"add belongs_to :user to `app/models/user.rb`"
but I think you meant to add it to `app/models/bookmark.rb`

**Comment by andreapavoni** [comment]
hi there,

thank you for your interest. the typo was already fixed here: http://andreapavoni.com/blog/2013/8/a-rails-4-tutorial-application-for-beginners/

cheers

**Comment by 2016rshah** [comment]
Great, thanks for the quick response!
